build: Don't patch GCC source if no update requested
As it doesn't touch patched source in any way, we shouldn't double
patch it too. It'll fail instead.

Signed-off-by: Albert I <kras@raphielgang.org>

diff --git a/build b/build
--- a/build
+++ b/build
@@ -567,7 +567,9 @@ function setup_env() {
         GCC_PATCH="GCC_10_up"
     fi
 
-    patch -Np1 < "${ROOT}"/patches/${GCC_PATCH}.patch || die "Failed to patch GCC source!"
+    if [[ -z ${NO_UPDATE} ]]; then
+        patch -Np1 < "${ROOT}"/patches/${GCC_PATCH}.patch || die "Failed to patch GCC source!"
+    fi
 
     cd ..
 
